#!/bin/bash
#v1.1

#Imposta l'interfaccia di rete predefinita
interface="en0"

if [ $# -gt 0 ]; then
  interface="$1"
fi

MAC=$(ifconfig "$interface" | awk '/ether/{print $2}')
echo "Indirizzo MAC di $interface: $MAC"

if [ $# -gt 1 ]; then
  input_mac="$2"

  #Controlla se il MAC è valido piccolo aiutino da wikipedia
  if ! [[ $input_mac =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]]; then
    echo "Invalid MAC"
    exit 1
  fi

  MAC="$input_mac"
else
  MAC=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
fi

#Imposta l'indirizzo MAC sulla scheda di rete
sudo spoof-mac set "$MAC" "$interface"

#Conferma l'effettivo cambio del MAC
MAC=$(ifconfig "$interface" | awk '/ether/{print $2}')

echo "Nuovo indirizzo MAC di $interface: $MAC"